name: deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    # if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - run: dotnet publish
      # - run: cd ClientApp && npm ci
      # - run: npm run build
      # - run: cd .. && dotnet publish
      # - run: npm run test

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /srv/pubkviz/
          remote_host: ec2-34-192-56-50.compute-1.amazonaws.com
          remote_user: ec2-user
          remote_key: "${{ secrets.PUBKVIZPROD_SSH_KEY }}"
